# SwiftLint Configuration for MarkerWalker
# Swift 6 / SwiftUI / SPM Multi-module Project

# Paths to exclude from linting
excluded:
  - .swiftpm
  - .build
  - App/.build
  - App/DerivedData
  - MarkerWalker/.build
  - MarkerWalker/.swiftpm

# Paths to include (optional, by default all Swift files are included)
included:
  - App
  - MarkerWalker/Sources

# Opt-in rules (rules that are not enabled by default)
opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - explicit_init
  - fatal_error_message
  - force_unwrapping  # 強制アンラップを警告（CLAUDE.mdの原則禁止に対応）
  - implicitly_unwrapped_optional
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo  # TODOコメントを許可
  - trailing_whitespace  # 末尾の空白は別ツールで管理

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 50
  error: 100

file_length:
  warning: 400
  error: 500
  ignore_comment_only_lines: true

type_body_length:
  warning: 300
  error: 400

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - x
    - y
    - z

# 強制アンラップの警告設定
force_unwrapping:
  severity: warning

# 暗黙的アンラップオプショナルの警告
implicitly_unwrapped_optional:
  severity: warning

# ネストの深さ制限（guardで早期returnを推奨）
nesting:
  type_level:
    warning: 2

# Cyclomatic Complexity（複雑度）
cyclomatic_complexity:
  warning: 10
  error: 20

# Custom rules (optional)
custom_rules:
  # 位置情報などのプライバシー情報をログに出さないための警告
  no_privacy_in_logs:
    name: "Privacy Information in Logs"
    regex: 'print\(.*(?:location|coordinate|latitude|longitude|user|email|phone)'
    match_kinds:
      - identifier
    message: "位置情報やユーザー情報をログに出力していないか確認してください"
    severity: warning
